---
title: "Lasso vs StepAIC"
author: "Berti Emilio"
date: "17/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dummy, include=FALSE}
library(tidyverse)
library(magrittr) #because power is in the pipes
library(MuMIn)
library(glmnet)
```

```{r libs, eval=FALSE}
library(tidyverse)
library(magrittr) #because power is in the pipes
library(MuMIn)
library(glmnet)
```

```{r main}
d <- read_delim("https://raw.githubusercontent.com/emilio-berti/monthly-programming-challenge/master/R/02/winequality-white.csv",
                delim = ";",
                col_types = cols())

# a bit of data exploration -------------
d %>% 
  pivot_longer(1:12, names_to = "Variable", values_to = "value") %>% 
  ggplot() +
  geom_histogram(aes(value), bins = 20) +
  facet_wrap(~ Variable, ncol = 3, scales = "free") +
  theme_minimal()

# better to log-transform some variables, imho
d %>% 
  mutate(chlorides = log10(chlorides),
         sulphates = log10(sulphates),
         `volatile acidity` = log10(`volatile acidity`)) %>% 
  pivot_longer(1:12, names_to = "Variable", values_to = "value") %>% 
  ggplot() +
  geom_histogram(aes(value), bins = 20) +
  facet_wrap(~ Variable, ncol = 3, scales = "free") +
  theme_minimal()

# let's scale also
d %<>% 
  mutate(chlorides = log10(chlorides),
         sulphates = log10(sulphates),
         `volatile acidity` = log10(`volatile acidity`)) %>% 
  scale() %>% 
  as_tibble()

# modelling -------------
m <- lm(quality ~ ., data = d)

# step-AIC
options(na.action = "na.fail")
aic_step <- dredge(m)
# more than one strongly-supported model. I should average, but
# I keep this simple and take only the first model.
aic <- lm(quality ~ `fixed acidity` + `free sulfur dioxide` +
            `residual sugar` + `volatile acidity` + alcohol +
            chlorides + density + pH + sulphates, 
          data = d)

# lasso
lambdas <- 10^seq(2, -3, by = -.1)
lasso <- cv.glmnet(as.matrix(d[, -which(names(d) == "quality")]), 
                   d$quality,
                   lambda = lambdas)
plot(lasso)
best_lambda <- lasso$lambda.min
lasso <- glmnet(as.matrix(d[, -which(names(d) == "quality")]), 
                d$quality,
                lambda = best_lambda)

aic_df <- tibble(var = aic$coefficients %>% 
                     names(),
                   coef = aic$coefficients %>% 
                     as.vector()) %>% 
  mutate(method = "Step AIC",
         var = gsub("`", "", var),
         low = confint(aic)[, 1],
         high = confint(aic)[, 2])
lasso_df <- tibble(var = coef(lasso) %>% 
                  as.matrix() %>%
                  rownames(),
                coef = coef(lasso) %>% 
                  as.matrix() %>% 
                  as.vector(),
                low = coef,
                high = coef) %>% 
  mutate(var = gsub("`", "", var),
         method = "LASSO")

res <- bind_rows(aic_df, lasso_df)

res %>% 
  filter(var != "(Intercept)",
         coef != 0,
         sign(low) == sign(high)) %>% #this removes unsignificant coefficients
  ggplot() +
  aes(var, coef, ymin = low, ymax = high, col = method) +
  geom_pointrange(position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("steelblue", "tomato")) +
  xlab("") +
  ylab("Coefficient") +
  coord_flip() +
  theme_minimal()
```